---
title: "Vektoren und Matrizen"
format:
  pdf:
    pdf-engine: pdflatex
    header-includes: |
      \rhead{Übungsblatt zu (3)}
      \fancypagestyle{plain}{% redefine plain to be same as fancy
        \rhead{Übungsblatt zu (3)}
      }
---

\setstretch{1.4}

## Vektoren

\begin{enumerate}
  \item Dokumentieren Sie alle in dieser Einheit eingeführten R-Befehle in einem R-Skript.
  \item Öffnen Sie die R Help-Seite der Funktion \texttt{c()}. Zu welchem R-Paket gehört \texttt{c()}?
  \item Erstellen Sie einen Vektor mit den Zahlen 1, 2, 3 mithilfe des Colon-Operators.
  \item Überlegen Sie sich zu jedem der vier Prinzipien der Indizierung in R ein Beispiel und dokumentieren Sie diese im R-Skript aus Aufgabe 1.
  \item Erzeugen Sie einen Vektor der Dezimalzahlen 0.0, 0.05, 0.10, 0.15, ..., 0.90, 0.95, 1.0.
  \item Wählen Sie mithilfe positiver Indizes die Elemente 0.0, 0.1, ..., 0.9, 1.0 dieses Vektors aus.
  \item Wählen Sie mithilfe negativer Indizes die Elemente 0.0, 0.1, ..., 0.9, 1.0 dieses Vektors aus.
  \item Wählen Sie die letzten 10 Elemente dieses Vektors aus.
  \item Erstellen Sie einen Vektor, der sowohl Zahlenwerte als auch fehlende Werte (\texttt{NA}) enthält, zum Beispiel \texttt{c(1, 2, NA, 19, NA, 41)}, und berechnen Sie die Summe aller Werte dieses Vektors mit der Funktion \texttt{sum()}.
  \begin{itemize}
    \item Warum gibt die Funktion als Ergebnis \texttt{NA} zurück? Recherchieren Sie dazu auf der Help-Page (\texttt{?sum}).
    \item Wie können Sie die Funktion \texttt{sum()} dazu veranlassen, die \texttt{NA}-Werte zu ignorieren und die Summe nur über die vorhandenen Zahlenwerte zu berechnen?
  \end{itemize}
  \item Erstellen Sie einen Vektor mit den Werten 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5 und 10.0 auf drei verschiedene Weisen. Wählen Sie anschließend die ungeraden Positionen (z.B. Position 1, 3, 5, usw., also die Werte 5.0, 6.0, 7.0, usw.) einmal mithilfe positiver und einmal mithilfe negativer Indizes aus und geben Sie die ausgewählten Werte aus.
  \item Zeigen Sie, dass der mit \texttt{u <- c(4, 5, 6)} definierte Vektor nicht vom Datentyp \texttt{character} ist.
\end{enumerate}

\newpage

## Matrizen

\begin{enumerate}
    \item Dokumentieren Sie alle in dieser Einheit eingeführten Befehle in einem R-Skript.
    \item Erzeugen Sie in R die Matrizen
$$
A = 
\begin{pmatrix}
4 & 3 & 2 & 1 \\
3 & 2 & 1 & 4 \\
2 & 1 & 4 & 3
\end{pmatrix}
\text{ und }
B = 
\begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0
\end{pmatrix}
$$
    \item Kopieren Sie die zweite Zeile von $A$ in einen Vektor.
    \item Kopieren Sie die erste und dritte Spalte von $B$ in eine 3 $\times$ 2 Matrix.
    \item Setzen Sie alle Nullen in $B$ auf -1.
    \item Setzen Sie die zweite Zeile von $A$ auf $(1\,2\,3\,4)$.
    \item Addieren Sie die Matrizen $A$ und $B$.
    \item Multiplizieren Sie Matrix $A$ mit 3.
    \item Konkatenieren Sie die Matrizen $A$ und $B$ zeilenweise.
    \item Konkatenieren Sie die Matrizen $A$ und $B$ spaltenweise.
    \item Öffnen Sie beide Matrizen im VSCode Table Viewer.
    \item Erstellen Sie zwei neue Matrizen $C$ und $D$ wie unten angegeben. Verwenden Sie Indizes, um jeweils eine Spalte der Matrix $C$ und eine Spalte der Matrix $D$ zu extrahieren. Kombinieren Sie diese beiden Spalten mithilfe der Funktion \texttt{cbind()} zu einer neuen Matrix $E$ und geben Sie die Matrix $E$ aus.
    \[
    C = 
    \begin{pmatrix}
    4 & 6 & 1 \\
    7 & 0 & 2 \\
    1 & 8 & 0
    \end{pmatrix}
    \qquad
    D = 
    \begin{pmatrix}
    7 & 0 & 3 \\
    9 & 9 & 0 \\
    1 & 3 & 6
    \end{pmatrix}
    \]
    \item Setzen Sie alle Einsen in Matrix $C$ auf \texttt{NaN} und bestimmen Sie mit der Funktion \texttt{is.nan()} und \texttt{sum()}, wie viele ungültige Zahlenwerte (\texttt{NaN}) die Matrix enthält. Geben Sie das Ergebnis aus.
\end{enumerate}
