---
title: "Maße zentrale Tendenz und Datenvariabilität"
format:
  pdf:
    pdf-engine: pdflatex
    header-includes: |
      \rhead{Übungsblatt zu (7)}
      \fancypagestyle{plain}{% redefine plain to be same as fancy
        \rhead{Übungsblatt zu (7)}
      }
---

\setstretch{1.4}

## Deskriptive Statistiken

\begin{enumerate}
\item Dokumentieren Sie alle in dieser Einheit verwendeten R-Befehle in einem R-Skript.
\item Laden Sie den Datensatz aus der Datei \texttt{psychotherapie\_datensatz.csv}. Fügen Sie dem Datensatz eine neue Spalte \texttt{Delta.BDI} hinzu, die die Differenz zwischen dem Pre- und Post-Wert enthält (Pre.BDI minus Post.BDI). \texttt{Delta.BDI} soll dabei so berechnet werden, dass positive Werte eine Verbesserung (Reduktion der Depressionswerte) widerspiegeln.
\item Berechnen Sie den Mittelwert, den Median und den Modalwert der Post-BDI-Daten. Speichern Sie diese drei Werte in separaten Variablen. Visualisieren Sie anschließend die Häufigkeitsverteilung der Post-BDI-Daten und diskutieren Sie in einem Kommentar in Ihrem R-Skript die berechneten Werte von Mittelwert, Median und Modalwert vor dem Hintergrund dieser Häufigkeitsverteilung.
\item Berechnen Sie die Spannbreite (Range) der Post-BDI-Daten. Berechnen Sie außerdem die Stichprobenvarianz und die Stichprobenstandardabweichung der Post-BDI-Daten. Verwenden Sie bei der Berechnung die Definitionen aus der Vorlesung.
\item Berechnen Sie deskriptive Statistiken für die Variable \texttt{Delta.BDI}. Erstellen Sie hierfür einen Dataframe, der die folgenden statistischen Kennzahlen enthält: die Stichprobengröße (\texttt{n}), das Maximum (\texttt{Max}), das Minimum (\texttt{Min}), den Median, den Mittelwert (\texttt{Mean}), die Varianz (\texttt{Var}) und die Standardabweichung (\texttt{Std}). Verwenden Sie bei der Bestimmung von Mittelwert, Varianz und Standardabweichung die Definitionen aus der Vorlesung.
\item Berechnen Sie deskriptive Statistiken für die Variable \texttt{Delta.BDI}, getrennt nach den beiden Therapiebedingungen \textquote{Klassisch} und \textquote{Online}. Erstellen Sie dazu einen Dataframe, der für jede Bedingung eine Zeile enthält und die statistischen Kennzahlen (Stichprobengröße, Maximum, Minimum, Median, Mittelwert, Varianz und Standardabweichung) als Spalten darstellt.

Gehen Sie dabei wie folgt vor: Legen Sie zunächst einen Vektor mit zwei Elementen an, der die Namen der Therapiebedingungen enthält, und initialisieren Sie einen leeren Dataframe mit dem Befehl \texttt{deskr\_stat <- data.frame()}. Verwenden Sie anschließend eine \texttt{for}-Schleife, um über die Therapiebedingungen zu iterieren. Filtern Sie in jeder Iteration der Schleife zunächst die Daten für die jeweilige Bedingung, berechnen Sie anschließend die bedingungsspezifischen deskriptiven Statistiken für \texttt{Delta.BDI} und tragen Sie die berechneten Werte in die entsprechenden Zeilen des Dataframes ein.

\textit{Hinweis:} Der resultierende Dataframe sollte folgende Werte enthalten:

\begin{table}[h!]
    \centering
    \begin{tabular}{lccccccc}
    \hline
             & n  & Max & Min & Median & Mean  & Var      & Std      \\ 
    \hline
    Klassisch & 50 & 12  & -1  & 6      & 6.16  & 7.075918 & 2.660060 \\ 
    Online    & 50 & 9   & 1   & 5      & 4.92  & 3.911837 & 1.977836 \\ 
    \hline
    \end{tabular}
\end{table}
\end{enumerate}

## Visualisierung deskriptiver Statistiken

\begin{enumerate}
\item Erstellen Sie ein Balkendiagramm mit Fehlerbalken, das die Mittelwerte und Standardabweichungen der Variable \texttt{Delta.BDI} für die beiden Therapiebedingungen \textquote{Klassisch} und \textquote{Online} zeigt. Extrahieren Sie dazu zunächst die Mittelwerte und Standardabweichungen aus dem in der vorherigen Sektion erstellten Dataframe mit den deskriptiven Statistiken. Nutzen Sie die Funktion \texttt{barplot()}, um die Mittelwerte als Balken darzustellen, und ergänzen Sie Fehlerbalken, die die Standardabweichungen anzeigen, mithilfe der Funktion \texttt{arrows()}. Achten Sie darauf, passende Achsenbeschriftungen und einen aussagekräftigen Titel für das Diagramm zu wählen. Speichern Sie das Diagramm im Unterordner \texttt{Abbildungen} als \texttt{balkendiagramm\_delta\_bdi.pdf}

\item Erstellen Sie Boxplots, die die Verteilung der \texttt{Delta.BDI}-Werte für die beiden Therapiebedingungen \textquote{Klassisch} und \textquote{Online} visualisieren. Nutzen Sie die Funktion \texttt{boxplot()} mit dem Funktionsargument \texttt{formula}, um die \texttt{Delta.BDI}-Werte nach Therapiebedingungen zu gruppieren und mit einem einzigen Befehl beide Boxplots nebeneinander in einem Diagramm darzustellen. Vergeben Sie passende Achsenbeschriftungen und einen aussagekräftigen Titel. Speichern Sie das Diagramm im Unterordner \texttt{Abbildungen} als \texttt{boxplots\_delta\_bdi.pdf}
\end{enumerate}
